services:
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  server:
    build: .
    depends_on:
      - db
    ports:
      - "${NODE_PORT}:3000"
      - "25565:25565"
      - "42230:42230"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c "npm run resetdb && npm run dev"
    restart: unless-stopped

volumes:
  pgdata:
