FROM node:22-alpine

ARG GATEWAY_PORT
ARG BLAZE_PORT

ENV GATEWAY_PORT=${GATEWAY_PORT}
ENV BLAZE_PORT=${BLAZE_PORT}

WORKDIR /app
COPY . .
RUN npm i -g pnpm prisma && pnpm install
EXPOSE ${GATEWAY_PORT} ${BLAZE_PORT} 42230
